version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: travel_to_db_testing
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run migrations and seeders
          command: npm run migrate:ci

      - run:
          name: Start server
          commant: ENV_SILENT=true npm start
          background: true

      - run:
          name: Run tests
          command: npm run test:ci
      - store_artifacts:
          path: test-results.xml
          prefix: tests

################### Workflow ###################
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - /^feature.*/
                - master
