version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: travel-to-db-test
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: copy env file
          command: cp .env.example .env

      - run:
          name: Run tests
          command: npm test
    - store_artifacts:
          path: test-results.xml
          prefix: tests

################### Workflow ###################
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - /^feature.*/
                - master
